# Generated by Django 3.2.9 on 2022-12-24 09:21

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('hostelName', models.CharField(choices=[('gh', 'Ghazali'), ('rz', 'Razi'), ('rm', 'Rumi'), ('at', 'Attar'), ('hv', 'Hajveri'), ('zk', 'Zakaria'), ('ft', 'Fatima'), ('as', 'Ayesha'), ('am', 'Amna'), ('kj', 'Khadija'), ('zb', 'Zainab')], max_length=2)),
                ('level', models.CharField(choices=[('ug', 'UG'), ('pg', 'PG')], max_length=2)),
                ('block', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('capacity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(600), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('hostelBlockName', models.CharField(max_length=15)),
                ('monthName', models.CharField(max_length=15)),
                ('billType', models.CharField(choices=[('MB', 'MessBill'), ('RB', 'RentBill')], max_length=2)),
                ('invoiceFile', models.FileField(upload_to='../save_invoices/')),
            ],
        ),
        migrations.CreateModel(
            name='notice_board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('d_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='outPass',
            fields=[
                ('cmsId', models.IntegerField()),
                ('From_date', models.DateField()),
                ('To_date', models.DateField()),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomNumber', models.IntegerField(validators=[django.core.validators.MaxValueValidator(450), django.core.validators.MinValueValidator(101)])),
                ('maxCapacity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('noOfResidents', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='room_change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_name', models.CharField(default='naam dydy bhai', max_length=30)),
                ('req_room', models.IntegerField(default=10)),
                ('with_name', models.CharField(default='naam dydy bhai', max_length=30)),
                ('with_room', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='rProblems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('cmsId', models.IntegerField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=40)),
                ('phoneNumber', models.CharField(blank=True, max_length=13)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('guardianName', models.CharField(max_length=40)),
                ('guardianPhoneNumber', models.CharField(max_length=13)),
                ('permenantAddress', models.TextField()),
                ('department', models.CharField(max_length=10)),
                ('roomNumber', models.IntegerField(default=10)),
                ('userAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('fullName', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('phoneNumber', models.CharField(max_length=13)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('userAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('date', models.DateField(default=datetime.date)),
                ('marking', models.CharField(choices=[('P', 'present'), ('A', 'absent')], max_length=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_form.student')),
            ],
        ),
    ]
