# Generated by Django 3.2.9 on 2022-12-18 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='hostelBlockName',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='basic_form.hostel'),
        ),
    ]
