# Generated by Django 3.2.9 on 2022-12-18 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_form', '0002_alter_manager_hostelblockname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='hostelBlockName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hostelBlockName',
        ),
    ]
