# Generated by Django 3.2.9 on 2022-12-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_form', '0003_auto_20221218_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roomNumber',
        ),
    ]
