# Generated by Django 3.2.9 on 2022-12-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_form', '0004_remove_student_roomnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cnicNumber',
        ),
    ]
