# Generated by Django 3.2.9 on 2022-12-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_form', '0005_remove_student_cnicnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
